ENDIAN_NATIVE = '='
ENDIAN_LITTLE = '<'
ENDIAN_BIG = '>'
ENDIAN_NETWORK = '!'

INT8_SIGNED = 'b'
INT8_UNSIGNED = 'B'
INT16_SIGNED = 'h'
INT16_UNSIGNED = 'H'
INT32_SIGNED = 'i'
INT32_UNSIGNED = 'I'
INT64_SIGNED = 'q'
INT64_UNSIGNED = 'Q'

FLOAT = 'f'
DOUBLE = 'd'

